### ISSUE TITLE
Why did created this repo?

### ISSUE THREAD

**Issue by Snimer** [examplehub/Python#13]
@shellhub 
I want to contribute to this repo. But first I should know How Can we create this different. 

Why did you started this repo? Means there is already this type of repo like the TheAlgorithms\Python.  I am not saying You shouldn't created this but just that What to do you want to different than other. So, I could get a clear understanding how can I contribute.

**Comment by realDuYuanChao** [comment]
This repository contains knowledge for learning python. e.g. python syntax. or other example. See https://github.com/examplehub/Python/tree/master/basics
